name: soooounds
region: nyc
services:
- name: api
  github:
    repo: hamhoagie/sooooounds
    branch: main
    deploy_on_push: true
  source_dir: server
  build_command: npm install
  run_command: npm start
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  - path: /health
  - path: /transform-image
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: OPENAI_API_KEY
    type: SECRET
  - key: REPLICATE_API_TOKEN
    type: SECRET

static_sites:
- name: web
  github:
    repo: hamhoagie/sooooounds
    branch: main
    deploy_on_push: true
  source_dir: client
  build_command: npm install && npm run build
  output_dir: dist
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_API_URL
    value: ${api.PUBLIC_URL}