name: soooounds
region: nyc
ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /
services:
- name: web
  github:
    repo: hamhoagie/sooooounds
    branch: main
    deploy_on_push: true
  source_dir: .
  build_command: cd server && npm install && cd ../client && npm install && npm run build
  run_command: cd server && npm start
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: OPENAI_API_KEY
    type: SECRET
  - key: REPLICATE_API_TOKEN
    type: SECRET
  http_path: /