name: soooounds
region: nyc
services:
- name: server
  github:
    repo: hamhoagie/sooooounds
    branch: main
    deploy_on_push: true
  source_dir: server
  build_command: npm install && npm run build || echo "No build script"
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: OPENAI_API_KEY
    type: SECRET
  - key: REPLICATE_API_TOKEN
    type: SECRET

static_sites:
- name: client
  github:
    repo: hamhoagie/sooooounds
    branch: main
    deploy_on_push: true
  source_dir: client
  build_command: npm install && npm run build
  output_dir: dist
  envs:
  - key: VITE_API_URL
    value: ${server.PUBLIC_URL}