name: soooounds
services:
- name: api
  source_dir: /server
  github:
    repo: hamhoagie/sooooounds
    branch: main
  build_command: npm install --production
  run_command: node index.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /api
  - path: /transform-image
  - path: /health
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: NPM_CONFIG_PRODUCTION
    value: "true"
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: REPLICATE_API_TOKEN
    scope: RUN_TIME
    type: SECRET

static_sites:
- name: web
  source_dir: /client
  github:
    repo: hamhoagie/sooooounds
    branch: main
  build_command: npm install && npm run build
  output_dir: dist
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_API_URL
    value: ${api.EXTERNAL_URL}